# library(shinydashboard)
# library(shiny)
# library(stringr)
# library(dplyr)
# library(ggplot2)
# library(tidyverse)
# library(lubridate)
# library(plotly)
# library(data.table)
# library(lubridate)
# library(RCurl)
# require(plotly)
# library(tidyr)
# library(ggplot2)
# library(forecast)
# library(tseries)
source("frontEnd.R")
source("backEnd.R")


shinyApp(ui, server)
